spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=game
    username: root
    password: root
  config:
    activate:
      on-profile: default
  devtools:
    add-properties: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
