spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=game
    username: root
    password: root
  devtools:
    add-properties: true
  profiles:
    active: dev
logging:
  level:
    web: DEBUG
#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG
#    io.r2dbc.postgresql.PARAM: DEBUG
